### PR TITLE
Add bootstrap script.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Add a script to setup the project and the necessary `Brewfile` and JavaScript to setup MongoDB correctly. Also, adjust the `README` to note that this script can be used and remove the existing steps which are done by this script.

### CODE REVIEW

**Comment by koraktor** [comment]
Thanks, that looks great.

Would you mind moving `braumeister.js` into `db/`?

Maybe there’s should be a note in the `README` that this script assumes macOS / Homebrew.

**Comment by MikeMcQuaid** [comment]
> Would you mind moving braumeister.js into db/?

Done!



> Maybe there’s should be a note in the README that this script assumes macOS / Homebrew.

It actually should work on Linux too but I think assuming Homebrew is reasonable given the project. 
Up to you, though!

**Comment by koraktor** [comment]
Looks like that file is missing now?

**Comment by koraktor** [comment]
Thanks!

**Comment by MikeMcQuaid** [comment]
Thanks for the merge 🙇

**Pull request merged**
